apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-poc-mysql
spec:
  selector:
    matchLabels:
      app: mes-poc-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mes-poc-mysql
    spec:
      containers:
      - image: mariadb:latest
        name: mes-poc-mysql
        envFrom:
        - configMapRef:
            name: mes-system-env
        - secretRef:
            name: mes-system-secrets
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim