apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-mysql
spec:
  selector:
    matchLabels:
      app: mes-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mes-mysql
        system: mes-system
    spec:
      containers:
      - image: mariadb:latest
        name: mes-system-mysql
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: mes-system-env
        - secretRef:
            name: mes-system-secrets
        volumeMounts:
        - name: mes-system-mysql-persistent-storage
          mountPath: /var/lib/mysqlx
      volumes:
      - name: mes-system-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mes-system-mysql-pv-claim