apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mes-system-mysql-pv-claim
  labels:
    app: mes-mysql
    system: mes-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi